- name: Backup Mikrotik Configuration
  hosts: mikrotik_router
  gather_facts: yes
    
  tasks:
    - name: Create a backup configuration file on router
      community.routeros.api:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        path: "system/backup/save"
        params:
          name: "ansible_backup"
      register: backup_result
        
    - name: Show the backup result
      debug:
        var: backup_result