name: CI Pipeline for Ansible Backup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Ansible
        run:  |
          sudo apt update
          sudo apt install -y ansible
          pip install ansible-lint

      - name: Run ansible-lint
        run: |
          ansible-lint mikrotik_backup.yml

      - name: Test Ansible Playbook
        run: |
          ansible-playbook -i inventory.yml mikrotik_backup.yml --syntax-check
